### ISSUE TITLE
Websocket连接出错, 未知错误, 请检查配置

### ISSUE THREAD

**Issue by fierywing** [LQBing/docker-cqhttp-mirai#3]
大佬遇到了个新问题
```
07:16:40 [WARNING] [CQHTTPMirai] Websocket连接出错, 未知错误, 请检查配置, 如配置错误请修正后重启mirai nulljava.nio.channels.UnresolvedAddressException
 07:16:42 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 07:16:42 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 07:16:42 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 07:16:42 [INFO] [NETWORK] ConfigPushSvc.PushReq: Success
 07:16:43 [WARNING] [CQHTTPMirai] Websocket连接出错, 未知错误, 请检查配置, 如配置错误请修正后重启mirai nulljava.nio.channels.UnresolvedAddressException
 07:16:46 [WARNING] [CQHTTPMirai] Websocket连接出错, 未知错误, 请检查配置, 如配置错误请修正后重启mirai nulljava.nio.channels.UnresolvedAddressException
 07:16:49 [WARNING] [CQHTTPMirai] Websocket连接出错, 未知错误, 请检查配置, 如配置错误请修正后重启mirai nulljava.nio.channels.UnresolvedAddressException
 07:16:52 [WARNING] [CQHTTPMirai] Websocket连接出错, 未知错误, 请检查配置, 如配置错误请修正后重启mirai nulljava.nio.channels.UnresolvedAddressException
^C 07:16:54 [INFO] [CQHTTPMirai] 反向Websocket模块已禁用
 07:16:54 [ERROR] [CQHTTPMirai] kotlin.UninitializedPropertyAccessException: lateinit property server has not been initialized
        at tech.mihoyo.mirai.web.websocket.WebSocketServer.close(WebsocketServer.kt:60)
        at tech.mihoyo.mirai.BotSession.close$cqhttp_mirai(Session.kt:72)
        at tech.mihoyo.mirai.PluginBase.onDisable(PluginBase.kt:127)
        at net.mamoe.mirai.console.plugins.PluginBase.disable$mirai_console(PluginBase.kt:153)
        at net.mamoe.mirai.console.plugins.PluginManager.disablePlugins(PluginManager.kt:58)
        at net.mamoe.mirai.console.plugins.PluginManager.disablePlugins$default(PluginManager.kt:55)
        at net.mamoe.mirai.console.MiraiConsole.stop(MiraiConsole.kt:147)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion$load$1.invoke(MiraiConsolePureLoader.kt:28)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion$load$1.invoke(MiraiConsolePureLoader.kt:16)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

登录完后会弹出这个错误 用的而是腾讯云, 在配置文件尝试过改HOST 0.0.0.0 ,172.17.0.1 ,172.0.0.1 都还是出同样的错误  VPS端口也全部已经打开

当我把设置文件里的地址从bot改成 bot.domin.com 后显示
```
07:44:15 [WARNING] [CQHTTPMirai] Websocket连接出错, 请检查服务器是否开启并确认正确监听端口, 将在3秒后重试连接, Host: bot.domain.com:8000-Client-Universal Path: /ws
 07:44:18 [WARNING] [CQHTTPMirai] Websocket连接出错, 请检查服务器是否开启并确认正确监听端口, 将在3秒后重试连接, Host: bot.domain.com:8000-Client-Universal Path: /ws
 07:44:22 [WARNING] [CQHTTPMirai] Websocket连接出错, 请检查服务器是否开启并确认正确监听端口, 将在3秒后重试连接, Host: bot.domain.com:8000-Client-Universal Path: /ws
 07:44:26 [WARNING] [CQHTTPMirai] Websocket连接出错, 请检查服务器是否开启并确认正确监听端口, 将在3秒后重试连接, Host: bot.domain.com:8000-Client-Universal Path: /ws
```

**Comment by LQBing** [comment]
bot.domain.com:8000只是举个例子，是访问你的bot的地址和端口，因为我不知道你的服务器域名、IP、端口是什么不可能给你写死的。

**Comment by fierywing** [comment]
但是我在REVERSE_HOST用了自己的服务器的公网IP不行,我尝试在REVERSE_HOST是127.0.0.1 或者127.17.0.1 这种本机IP也不行
因为以前用酷Q 在反向这里直接127.17.0.1加bot的端口就能连上了  第一次用MIRAI 麻烦大佬了
 ![QQ截图20200821172902](https://user-images.githubusercontent.com/18031223/90875509-d6d35480-e3d3-11ea-9559-fbe73022c915.png)
![20200821172522](https://user-images.githubusercontent.com/18031223/90875830-4d705200-e3d4-11ea-8182-276f50067093.png)

**Comment by LQBing** [comment]
等等，你用的这个？看那边的readme啊，为什么会跑这边来开issue？
REVERSE_HOST和REVERSE_PORT不用改，mirai不需要被外面访问，只要bot能访问就可以了。docker-compose起直接可以内部用bot这个名字访问的。
